### ISSUE TITLE
Page crash.

### ISSUE THREAD

**Issue by elijahlrc** [szhu/3030#1]
The page when you hover over the walls of the maze. /s

**Comment by szhu** [comment]
Whoa, that's really weird. Looks like it might be a Chromium bug: [crbug.com/533361](https://code.google.com/p/chromium/issues/detail?id=533361)

I'll update this issue when this gets fixed upstream. :)

**Comment by scott113341** [comment]
:+1:

**Comment by ivyreese** [comment]
:lollipop:

**Comment by tacone** [comment]
:cat:

**Comment by vikashbajaj** [comment]
It crashes my facebook tab aswell :laughing:

**Comment by szhu** [comment]
Usually Chrome runs each tab in a new process, but when you click a link that opens in a new tab, Chrome does not create a new process for that new tab. That's why your referrer tab is crashing as well.

**Comment by vikashbajaj** [comment]
Ok, you guys should try posting as a link on a group on Facebook, so when facebook will try to load a preview on whosever feed it choses to show this post on, their tab will crash :smiling_imp:

**Comment by kernel-io** [comment]
when is this going to be fixed? this is worthless to me if it keeps crashing!!

**Comment by danieltanfh95** [comment]
Isn't the game is supposed to crash when we hover over the link? :laughing:

**Comment by szhu** [comment]
For now, yes, but it's a serious Chrome bug that needs fixed to be soon as possible. Unfortunately, there's nothing I can do about this for now. I will update this issue when it gets fixed upstream.

**Comment by dav-s** [comment]
I think somebody found a solution [here](http://github.com/%%30%30) :)

**Comment by lukerollans** [comment]
@EpicDavi If a comment could be liked..

**Comment by madelinecameron** [comment]
@EpicDavi Jerk. I fell for that.

**Comment by szhu** [comment]
This issue was also reported here:  
https://www.reddit.com/r/programming/comments/3lqied/3030_a_game/cv8iz1i?context=1

**Comment by felipegtx** [comment]
I'm confused on how to proceed when you create an issue that is related to an error that is actually the main feature of the repo.

**Comment by joshmanders** [comment]
Ohhhh @EpicDavi totally got me. :100:

**Comment by valenfys** [comment]
> I will update this issue when it gets fixed upstream.

New version of Chrome just came out (45.0.2454.99) and the ~~bug~~ API seems to still work

**Comment by szhu** [comment]
I can confirm that feature still works in 45.0.2454.99.

**Comment by szhu** [comment]
**This bug is fixed in Chrome 45.0.2454.101.**

https://code.google.com/p/chromium/issues/detail?id=533361#c86

Thanks for playing, everyone!
