### ISSUE TITLE
Full browser crash on Windows

### ISSUE THREAD

**Issue by smiley** [szhu/3030#12]
You should note in the `README.md` (above the map) that this crashes Chrome **entirely** on Windows. (not a single tab, but all `chrome.exe` processes due to an RPC error) The surprise might spoil the fun for some people. :neutral_face:

**Comment by jwthomson** [comment]
What version of Chrome are you running? Only the one tab crashes for me. (Windows 7, Chrome 45.0.2454.85 m)

Example : http://gfycat.com/LeanWarpedGreyhounddog

**Comment by kurtextrem** [comment]
Same here.

**Comment by DDuarte** [comment]
Window 10, Chrome 46.0.2490.33 beta-m (64-bit), only one tab crash as well

**Comment by louh** [comment]
Windows 10, Chrome 45.0.2454.93 m. All of Chrome crashes instantly.

**Comment by cybrox** [comment]
Windows 7, Chrome 47.0.2503.0 dev-m (64-bit) still has the issue, only crashes one tab though.

**Comment by smiley** [comment]
Same version as @louh, same OS, same crash. Looks like it's a problem with 45.0.2454.**93** m

**Comment by danielhickman** [comment]
Same here. http://gfycat.com/PettyFlakyBassethound

**Comment by towerofnix** [comment]
Interesting thing is it doesn't happen in OS X (OS X Yosemite, Chrome Canary 47.0.2515.0). Don't know if maybe it just has to do with running Canary though.

**Comment by mgol** [comment]
> Don't know if maybe it just has to do with running Canary though.

Nah. I've tried with 45.0.2454.93 on OS X 10.11 and only one tab crashes.

**Comment by szhu** [comment]
Confirmed entire-browser crash on Windows 8: 46.0.2490.33 beta-m (64-bit)

**Comment by rtf6x** [comment]
Windows 10, Chrome 45.0.2454.99 m: only one tab crashes.

**Comment by metarmask** [comment]
Only crashes one tab on Chrome OS version 46.0.2490.33 beta

**Comment by szhu** [comment]
Hey @metarmask: if you put `http://a/%%30%30` into the address bar, does it crash your entire OS?

**Comment by metarmask** [comment]
Yes it does.

**Comment by fduraibi** [comment]
If it is crashing the whole browser then you are playing in Hardcore mode, change to medium to crash just the tab. Easy mode will show a warning only.

**Comment by adavis444** [comment]
Can anyone, possibly @louh or @smiley, confirm that the entire Chrome browser crashes when playing the game or hovering over a URL? A directly typed URL will always crash the Chrome and Opera browsers, as far as I am aware.

Only the tab crashes playing the game/hovering over the URL in all of the following versions for me:
OS: Windows 10 (64-bit)
Chrome 45.0.2454.93 m (Same OS and version as @louh and @smiley, who experienced a full browser crash)
Chrome 45.0.2454.99 m (Most recent)
Opera 32.0.1948.44 (Most recent)

In the absence of any full browser crashes, the issue could be considered closed, possibly with a note of the differing severity of crash problems at the bottom of the readme.

**Comment by kurtextrem** [comment]
45.0.2454.99 m
full browser crash. Win 7 x64 professional.

**Comment by xmesaj2** [comment]
Chrome 47.0.2517.0 canary (64-bit) & Microsoft Windows [Version 10.0.10240]

Game is not crashing browser anymore. The magic is gone.

**Comment by louh** [comment]
I'm now on Version 45.0.2454.99 m, the browser is still fully crashing on mine.

**Comment by louh** [comment]
I also have Chrome Canary (47.0.2517.0 canary (64-bit)) - it does not crash there.

**Comment by towerofnix** [comment]
Oh yes. I'm on a Mac and when I type in the URL it kills my browser. (Actually, it doesn't let me open Canary until I restart my entire computer or logout-login!) If I just hover over the link it crashes my tab but not the rest of the game.

**Comment by szhu** [comment]
**This bug is fixed in Chrome 45.0.2454.101.**

https://code.google.com/p/chromium/issues/detail?id=533361#c86

Thanks for playing, everyone!

**Comment by towerofnix** [comment]
Aww.. twas fun. :)
