### ISSUE TITLE
x3030 : Maze game for Google Chrome based on that bug

### ISSUE THREAD

**Issue by pravj** [szhu/3030#22]
Hi @szhu,

Inspired from your project, I have made an attempt on a game where mazes are not fixed, hence generated. [x3030](https://github.com/pravj/x3030).

Mazes are generated by the [Recursive division method](https://en.wikipedia.org/wiki/Maze_generation_algorithm#Recursive_division_method).
Right now, I'm letting users play with any random maze among 100 generated mazes.

Posting it here as I thought you would be kind enough to add it in the _further reading_ section and we can discuss more possible things/issues, if any.

:octocat:

**Comment by szhu** [comment]
Yes, that would be cool! Want to give me the link to it?

**Comment by pravj** [comment]
Ohh my, I missed that. Feeling sleepy.

Here is the [project](https://github.com/pravj/x3030) and here you can play it online, [x3030](https://x3030.herokuapp.com).

**Comment by szhu** [comment]
Heads-up, the new Chrome update fixes the bug :(

**Comment by pravj** [comment]
Yeah, I saw it in the discussion they were having.
Is it rolled back to all of us? Mine is still facing the issue though.

**Comment by szhu** [comment]
Go to About Google Chrome and your update should start downloading.

As for how to work around the fix, I'm going to try this: https://github.com/szhu/3030/issues/9#issuecomment-142182184

**Comment by pravj** [comment]
That hacky solution looks cool, I'll shift to it tomorrow.

**Comment by szhu** [comment]
I added a link to your game in the lastest doc :)
