### ISSUE TITLE
cl.ly demo link isn't working

### ISSUE THREAD

**Issue by szhu** [szhu/3030#3]
Looks like the video is too popular. Working to get this resolved!

![screen shot 2015-09-20 at 6 43 17 pm](https://cloud.githubusercontent.com/assets/1570168/9984144/8324ee10-5fc7-11e5-8a50-502674df19a8.png)

**Comment by szhu** [comment]
:lollipop: :lollipop: :lollipop: 

![screen shot 2015-09-20 at 6 44 55 pm](https://cloud.githubusercontent.com/assets/1570168/9984158/ba3e847e-5fc7-11e5-9fd3-6a6969d67b55.png)

**Comment by szhu** [comment]
![screen shot 2015-09-20 at 7 26 52 pm](https://cloud.githubusercontent.com/assets/1570168/9984537/18acd0dc-5fce-11e5-9335-a3122cf948fb.png)

**Comment by GaiusCoffee** [comment]
Why not YouTube? :confused:

**Comment by szhu** [comment]
I don't have a YouTube or Vimeo account that I'm comfortable with making public. Otherwise that would have been my natural choice. Also, CloudApp seems pretty enthusiastic about removing the limits for the video :)

**Comment by szhu** [comment]
I'll host it as a GIF on Imgur. Problem solved. Thanks!

**Comment by szhu** [comment]
Here's a record of the number of views that the screencast got before being shut down:

![screen shot 2015-09-20 at 6 53 15 pm](https://cloud.githubusercontent.com/assets/1570168/9989215/87798108-600b-11e5-9d5a-5dcdac737829.png)
