### ISSUE TITLE
Odd, I don't see trees for some reason

### ISSUE THREAD

**Issue by CptSpaceToaster** [szhu/3030#4]
![#NotAllTrees](http://i.imgur.com/dq8SgeI.jpg)

Chrome: Version 45.0.2454.85 m

Did I internet wrong somehow?

**Comment by szhu** [comment]
What operating system are you using? It seems like none of the fonts you have installed have that emoji available.

**Comment by deckar01** [comment]
I am able to repro the missing tree emoji on Windows 7. Works correctly on iOS.

**Comment by szhu** [comment]
Okay, I'm considering changing the emojis to images. Thanks for your report!

**Comment by deckar01** [comment]
CDN hosted emojis:
Evergreen Tree: http://twemoji.maxcdn.com/16x16/1f332.png
Lollipop: http://twemoji.maxcdn.com/16x16/1f36d.png

**Comment by szhu** [comment]
Hm, those look kind of small. I'll accept these alternatives:
- Larger versions of these
- Instructions for extracting full-size emojis from my computer
- Hand-drawn versions :)

**Comment by CptSpaceToaster** [comment]
:+1:
