### ISSUE TITLE
:lollipop: should be a :bear: 

### ISSUE THREAD

**Issue by cycomachead** [szhu/3030#6]
Because, then it's like :bear: vs :evergreen_tree:

**Comment by szhu** [comment]
Hm… I like it! Can you find good images of these in high resolution or vector format? :bear:

**Comment by szhu** [comment]
Wait… Github replaces those with images. Nice!

**Comment by cycomachead** [comment]
Yes! :+1:

**Comment by szhu** [comment]
https://www.reddit.com/r/programming/comments/3lrrtr/google_chromes_3030_the_game/cv8tv8q

senpai has noticed us
