### ISSUE TITLE
Does not work in Firefox and new version of Chrome

### ISSUE THREAD

**Issue by danmana** [szhu/3030#9]
Kappa :)

**Comment by szhu** [comment]
That sucks! Unfortunately this game relies on an undocumentated Google Chrome API that the Firefox devs may not want to support. 

One problem towards adoption by Firefox is that Chrome keeps gives each tab its own process. However, Firefox does not, and so each tab is incapable of crashing on it's own -- it's either nothing or the entire browser. It's understandable that a browser crash would damage the integrity of the browser. 

If there are upsteam updates from Mozilla, I will update here as well.

**Comment by danmana** [comment]
Too bad browsers like Firefox don't implement new and cool APIs like Chrome does; don't even get me started on IE.

I really like this feature of being able to link directly to the "Aw, Snap!" page. 
Such a productivity booster, I'll use it everyday from now on. :P

**Comment by cybrox** [comment]
@danmana I always though the Internet Explorer on my work machine is broken for some reason, but it seems to be a unique version that includes this feature.

Steps to reproduce on (my) IE10
- Open Internet Explorer 10

**Comment by John-Lin** [comment]
I also found Safari can't work. :laughing:

**Comment by lockys** [comment]
The brand new Edge browser could not work likes a charm.
It's so sad. :disappointed: 
This game is awesome, and should be considered to make a version that cross the browser!

**Comment by danmana** [comment]
@cybrox I think you might have this URL set as your homepage. Probably some awesome adware added it for you. 

I like adware, such a nice way to discover new toolbars for my browser, and also who doesn't like being surprised with a new homepage once in a while, such a nice way to discover the internet.

**Comment by nicolasgarnil** [comment]
+1 please fix

**Comment by lockys** [comment]
Mimic the effect of %30%30, it may crosses the browser :smile: 
https://github.com/lockys/3030.js

**Comment by jpnauta** [comment]
+1

**Comment by szhu** [comment]
@lockys that is actually amazing

**Comment by szhu** [comment]
This game doesn't work in the new version of Chrome either. I've edited the title to reflect that.

**Comment by szhu** [comment]
The official game URL is now http://szhu.github.io/3030/, which "does work" for Firefox and Chrome.

Thanks for playing, everyone!

**Comment by lockys** [comment]
@szhu that's awesome work! can't wait for your PR to improve 3030.js inspired by you :smile:

**Comment by mgol** [comment]
I don't think this is fixed in 45.0.2454.101. Hovering over the trees at https://github.com/szhu/3030 no longer crashes the tab but it still does at http://szhu.github.io/3030/.

Same on Canary 47.0.2519.0

**Comment by mgol** [comment]
Ah, this is just fake, lol. :D

**Comment by szhu** [comment]
You can thank @lockys for the convincing visual!
